registration:
  startBalance: 100
  defaultUsers:
    - username: user1
      password: asdasd
      balance: 1000
    - username: user2
      password: asdasd
      balance: 100

database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/bank
  username: postgres
  password: postgres