spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bank
    driverClassName: org.postgresql.Driver

liquibase:
  changelog:
    location: classpath:/database/changelog-master.xml
  schema: bank

registration:
  startBalance: 100
  defaultUsers:
    - username: user1
      password: asdasd
      balance: 1000
    - username: user2
      password: asdasd
      balance: 100

